defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  -  _self_

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
    direction: maximize  # or 'minimize' depending on your optimization goal
    study_name: soyseg
    storage: sqlite:///soyseg_final.db  # Set the database for storing Optuna studies
    n_trials: 20
    n_jobs: 1
    params:
      head: ${hydra.sweeper.suggest_categorical:head, ["deeplabv3plus", "fpn"]}
      backbone: ${hydra.sweeper.suggest_categorical:backbone, ["mit_b1", "effnetb0"]}

paths:
  train_folder: ${hydra:runtime.cwd}/soy_seg_v1/train/data
  train_target_folder: ${hydra:runtime.cwd}/soy_seg_v1/train/labels
  val_folder: ${hydra:runtime.cwd}/soy_seg_v1/val/data
  val_target_folder: ${hydra:runtime.cwd}/soy_seg_v1/val/labels

model:
  head: ${hydra:sweeper.head}  # this will be dynamically replaced
  backbone: ${hydra:sweeper.backbone}  # this will be dynamically replaced
  strategy: freeze

train:
  learning_rate: 0.001
  optimizer: adam
  batch_size: 32
  num_workers: 8

transform:
  size: 256
  crop_factor: 1
  blur_kernel_size: 1
  p_color_jitter: 0
  rand_rot: False
  scaling: False